const ActionTypes = {
  MOVE_PIECE: 'MOVE_PIECE',
  SELECT_PIECE: 'SELECT_PIECE',
  UNSELECT_PIECE: 'UNSELECT_PIECE',
  SWITCH_TURN: 'SWITCH_TURN',
  SET_WON_GAME: 'SET_WON_GAME',
  NEW_GAME: 'NEW_GAME',
  CAPTURE_PIECE: 'CAPTURE_PIECE',
};

export default ActionTypes;
